version: "3.8"

services:
  django:
    image: byeongyeongtae/pbl2-django:latest
    container_name: pbl2-django
    restart: always
    networks:
      - mojadol-network
    ports:
      - "4401:4401"
    volumes:
      - /home/bgt/django/.env:/app/.env
      - /home/bgt/django/kobart_model.pth:/home/bgt/django/kobart_model.pth
      - /home/bgt/django/shape_predictor_68_face_landmarks.dat:/home/bgt/django/shape_predictor_68_face_landmarks.dat


networks:
  mojadol-network:
    external: true